image: python:3.9.6

stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python -V
  - pip install -U pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Build stage completed"

test:
  stage: test
  script:
    - ./run_tests.sh

pages:
  stage: deploy
  script:
    - pip install -U sphinx sphinx_rtd_theme
    - cd documentation
    - sphinx-build -b html source/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: ${{ CI_COMMIT_BRANCH == main }}